[package]
name = "babel-interfaz"
version = "0.2.1"
edition = "2021"
license = "LicenseRef-Proprietary"

[lib]
name = "babel_interfaz_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri               = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde               = { version = "1.0", features = ["derive"] }
serde_json          = "1.0"

aes-gcm      = "0.10"
argon2       = { version = "0.5", features = ["password-hash"] }
hkdf         = "0.12"
sha2         = "0.10"
hmac         = "0.12"
rand         = "0.8"
hex          = "0.4"
zeroize      = { version = "1.7", features = ["derive"] }
pdf-extract  = "0.7"
lopdf        = "0.32"
pdfium-render = "0.9.3"
docx-rs      = "0.4"
imap         = { version = "=3.0.0-alpha.15", features = ["native-tls"] }
native-tls   = "0.2"
mailparse    = "0.14"
rustls       = "0.22"
webpki-roots = "0.26"
rcgen        = "0.12"
chrono       = { version = "0.4", features = ["serde"] }
rpassword    = "7"
base64       = "0.22"
hostname     = "0.3"
num_cpus     = "1.16"
dirs         = "5.0"
sysinfo      = "0.29"
uzers        = "0.12"
tokio        = { version = "1", features = ["full"] }
lettre = { version = "0.11", features = ["smtp-transport", "builder", "tokio1-native-tls"] }
ureq = { version = "2.9", features = ["json"] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2.3.5"
tauri-plugin-deep-link = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
log = "0.4"
env_logger = "0.11"
zip = "8.6.0"
tesseract = "0.14"
image = "0.25"
zstd = "0.13"
libc  = "0.2"
pbkdf2 = { version = "0.12", features = ["hmac"] }
ttf-parser   = "0.25"
subsetter    = "0.2"
flate2       = "1"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
core-foundation-sys = "0.8"

[profile.release]
opt-level     = 3
strip         = true
lto           = true
codegen-units = 1
